### ISSUE TITLE
Suggestion: Automatically choose a world on connection to a server.

### ISSUE THREAD

**Issue by thenolle** [MamiyaOtaru/voxelmap#41]
As you can see when you connect to a server it says you this message:
![image](https://user-images.githubusercontent.com/61505071/99854837-dd659980-2b85-11eb-9079-e3068efe264b.png)

I think it would be amazing if we could, no matter how, make it so it selects automatically the world for us at connection.
It could be through a config file, or through another type of file but It is quite annoying when you log out and back in (when you afk for exemple and get kicked) and you must RE-select your world.

I don't know if it is possible but if it is, I would love to see this feature!

**Comment by thenolle** [comment]
By the way, I play on 1.12.2 with this mod so, if it is possible to do it in 1.12.2, I would love it!

**Comment by xJon** [comment]
@TheNolle Did anything change that you closed the issue?
