### ISSUE TITLE
[Fabric 1.16.4] NullPointerException in GameVariableAccessShim on startup.

### ISSUE THREAD

**Issue by StarsDown64** [MamiyaOtaru/voxelmap#46]
The mod was working fine until I went and updated all my other mods (suggests to me a possible issue w/ new fabric API). The game crashes just after launch. [Crashlog](https://gist.github.com/StarsDown64/6eda64d40dbe11b0589ea48b2861169e). This is a copy of comment [2902](https://www.curseforge.com/minecraft/mc-mods/voxelmap?comment=2902) and [2907](https://www.curseforge.com/minecraft/mc-mods/voxelmap?comment=2907) from the curseforge page (I didn't know the github existed, although this doesn't exactly look used).

Fabric: 0.11.1-1.16.4
Fabric API: 0.29.3+1.16
Voxelmap: 1.10.14

**Comment by hugeblank** [comment]
This issue persists in the latest version of voxelmap (1.10.15)

**Comment by StarsDown64** [comment]
AFAIK this was fixed in an update of architectury, as it was caused by it. Closed with [architectury/architectury-api#35](https://github.com/architectury/architectury-api/issues/35)

**Comment by hugeblank** [comment]
@StarsDown64 I don't have architectury installed. Attached is the crash report generated when running:
[crash-2021-04-19_15.37.28-client.txt](https://github.com/MamiyaOtaru/voxelmap/files/6342629/crash-2021-04-19_15.37.28-client.txt)

**Comment by StarsDown64** [comment]
You do have architectury installed. Look at line 43 of your crash log. "architectury: Architectury 1.5.105"
This was fixed in architectury v1.9.132.

**Comment by hugeblank** [comment]
Thanks for alerting me of that, I guess one of the mods I added automatically downloaded it? It definitely wasn't in my mods folder.

Everything works as intended after installing the latest version of Architectury :D
